apiVersion: 1
datasources:
  - name: FinSight Postgres
    uid: finsight-pg
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: finsight
    isDefault: true
    secureJsonData:
      password: finsight
    jsonData:
      database: finsight
      sslmode: disable
      postgresVersion: 1600
